nodeLinker: node-modules

plugins:
  - checksum: 14a220afbd47de5a2b6db63e10e90fe70d1db1e8bb689be21c41dacb87e43e412b9e941bedfc9f0554323eefa1721fa663d64b785e4eda2fa89613c994437008
    path: .yarn/plugins/yarn-up-all-plugin.cjs
    spec: 'https://github.com/e5mode/yarn-up-all/releases/download/1.1.0/index.js'

yarnPath: .yarn/releases/yarn-4.1.1.cjs
